server:
  port: 8000

spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:mysql://localhost:3307/cambio_service?useTimezone=true&serverTimezone=UTC
    username: cambio
    password: cambio
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

