server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/osvaldsoza/config-server-application-ms
          search-paths:
            - 'greeting-service*'
